server {
    server_name @DOMAINE@;

    client_max_body_size 50M;
    client_body_buffer_size 128k;
    
    proxy_connect_timeout 300;
    proxy_send_timeout 300;
    proxy_read_timeout 300;
    send_timeout 300;

    access_log /var/log/nginx/whisper-api-access.log;
    error_log /var/log/nginx/whisper-api-error.log;

    location / {
        proxy_pass http://127.0.0.1:@PORT@;
        proxy_http_version 1.1;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /health {
        proxy_pass http://127.0.0.1:@PORT@/health;
        access_log off;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/@DOMAINE@/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/@DOMAINE@/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = @DOMAINE@) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name @DOMAINE@;
    return 404; # managed by Certbot


}